### ISSUE TITLE
Carthage Issues

### ISSUE THREAD

**Issue by mommyme** [ruslanskorb/RSKImageCropper#154]
Have you had a chance to check if this is building correctly wit Carthage lately? When I run 'carthage update' from the terminal, every other framework updates, but RSKImageCropper does not pull the latest info, and I get errors 'symbol(s) not found for architecture x86_64' when i compile. The errors are resolved when I simply remove RSKImageCropper from the cartfile and the app.

**Comment by kndl** [comment]
I had this same problem and I managed to resolve it. The issue is that Carthage manages a bare repository within its cache directory, which it then checks out to the working directory inside your project at `Carthage/Checkouts`. That checkout process does not clean up old files that are no longer in the repository.

To fix it, you should be able to do `rm Carthage/Checkouts/RSKImageCropper/RSKImageCropper/module.modulemap`. (There should be a file left in that directory named `RSKImageCropper.modulemap`.)

**Comment by ruslanskorb** [comment]
@mommyme Have you solved the issue?

**Comment by mommyme** [comment]
Was this a user bug or something that should possibly be handled within the Carthage process?
