### ISSUE TITLE
Size of the cropping rect is too small

### ISSUE THREAD

**Issue by stp-ios-gda** [ruslanskorb/RSKImageCropper#187]
When I zoom in to maximum and crop the image, size of the cropped image is lesser than it should according to the values provided in datasource methods. The problem is caused by taking

` CGFloat maxScale = MAX(xScale, yScale); ` when calculating max possible scale. If we replace this with ` CGFloat maxScale = MIN(xScale, yScale); `, then cropped rect when image is zoomed in to maximum will be exactly as value provided by datasource methods.

**Comment by ruslanskorb** [comment]
The mask rect and the movement rect do not specify the final size of the cropped image. They are using to generate and display the mask.

**Comment by ruslanskorb** [comment]
To get an image with the specific minimum size you need to use **RSKImageCropper** to crop the original image and then if needed manually scale the cropped image up to the minimum output size.

**Comment by ruslanskorb** [comment]
In your case the user will not always be able to select a specific part of the image. Also, there is a case where the original image may have a size smaller than the mask size.

**Comment by ruslanskorb** [comment]
@stp-ios-gda 

So, I decided not to add this functionality to the main repo of **RSKImageCropper**. But you can always do it in your own fork.

Anyway, thank you for collaborating!

**Comment by borkuslav** [comment]
Actually zoom doesn't affect movement area so every part of the image will be selectable. Anyway thanks for you work, I appreciate your library very much!

**Comment by ruslanskorb** [comment]
@borkuslav 

Probably, I put it not quite clear. The problem is that the accuracy of the selection of the required area in your case is reduced.

This is the first case:

`CGFloat maxScale = MAX(xScale, yScale);`

![simulator screen shot - iphone 7 - 2018-01-25 at 19 52 24](https://user-images.githubusercontent.com/1182823/35402624-40616414-020e-11e8-9cd1-9b3f9d3889d3.png)

`CGFloat maxScale = MIN(xScale, yScale);`

![simulator screen shot - iphone 7 - 2018-01-25 at 19 54 34](https://user-images.githubusercontent.com/1182823/35402623-3f744bfc-020e-11e8-93fd-b3c0543448f5.png)

And this is the second case when the height of the original image is less than the height of the mask:

`CGFloat maxScale = MAX(xScale, yScale);`

![simulator screen shot - iphone 7 - 2018-01-25 at 20 31 37](https://user-images.githubusercontent.com/1182823/35403136-d84981ac-020f-11e8-8376-7fdc9d915200.png)

`CGFloat maxScale = MIN(xScale, yScale);`

![simulator screen shot - iphone 7 - 2018-01-25 at 20 23 29](https://user-images.githubusercontent.com/1182823/35403131-d3c780f2-020f-11e8-89ca-c263bd7c2bd1.png)

**Comment by borkuslav** [comment]
Yeah, in some cases zoom range is much reduced. I see your point now. Thanks for sharing examples.
