### ISSUE TITLE
RSKImageCropViewController.m iOS 11.3 Depreciation Fixes

### ISSUE THREAD

**Issue by stoner221** [ruslanskorb/RSKImageCropper#188]
Line 140 : `self.automaticallyAdjustsScrollViewInsets = NO;` Should be replaced with `self.imageScrollView.contentInsetAdjustmentBehavior = NO;`

Line 163: `[application setStatusBarHidden:YES];` Should be  `application.statusBarHidden = YES;`

Line 187: `[application setStatusBarHidden:self.originalStatusBarHidden];` Should be  `application.statusBarHidden = self.originalStatusBarHidden;`

**Comment by Chana719** [comment]
Hello, thank you very much for your open source, you are doing well! I recently used your framework, would like to add some features on the basis of this, but failed to achieve, and then would like to ask a question, if I zoom the picture into the crop box, this picture can be arbitrarily moved in the box, or Image right instead of center, and then confirm the crop, display there is a problem, or, instead of the top of the picture offset to the center, cropping is the same problem! All of the above cutting zoom function, if you do not quite understand what I said, you can refer to the next print studio cutting function, I want to achieve it this style 😊, trouble you can give me some advice? Hope to receive your reply! Thank you!

**Comment by ruslanskorb** [comment]
@stoner221 I will look at it when the new version of Xcode will be publicly available.

@Chana719 Sorry, but I didn't understand what is your problem and what are you trying to achieve.

**Comment by Chana719** [comment]
I have already solved, thank you for your reply!

**Comment by ruslanskorb** [comment]
@stoner221 You are getting these errors because of your deployment target is equal or greater than iOS 11.0.

Minimum deployment target supported by **RSKImageCropViewController** is iOS 6.0.

In your case you can:
1) Ignore these errors.
2) Add `inhibit_all_warnings!` to your **Podfile**.
