### ISSUE TITLE
Define a minimum output size?

### ISSUE THREAD

**Issue by Arvkon** [ruslanskorb/RSKImageCropper#52]
Instagram photos are 640 x 640 pixels in size. I would like to make this the minimum size that an image can be cropped to. Could you (or anyone) suggest how I might go about achieving this?

**Comment by ruslanskorb** [comment]
Hello Arvid,

Sorry for the delay.
I will think about it in the coming weekend.
Currently, you can try to add the following code at [this line](https://github.com/ruslanskorb/RSKImageCropper/blob/master/RSKImageCropper/RSKImageScrollView.m#L211):

```obj-c
if (boundsSize.width < boundsSize.height) {
    maxScale = MIN(maxScale, boundsSize.width / 640.0);
} else {
    maxScale = MIN(maxScale, boundsSize.height / 640.0);
}
```

Sincerely,
Ruslan

**Comment by Arvkon** [comment]
You, sir, are a gentleman! Your suggestion worked like a charm =)

I made a fork with your code and a minOutputSize property: https://github.com/Arvkon/RSKImageCropper/commit/e590f8ad178bf6a82ce7e3db5a6d5af1604c60f1

**Comment by ruslanskorb** [comment]
:smiley: :thumbsup:

**Comment by perlasivakrishna** [comment]
How to set Min and Max Zoom in Swift ?

**Comment by ruslanskorb** [comment]
No. There aren't.

You should not limit the size of the image when cropping.

Instead of this, to get an image with the specific minimum size you need to use **RSKImageCropper** to crop the original image and then if needed manually scale the cropped image up to the minimum output size. This will allow the user to select any desired part of the image.
