### ISSUE TITLE
Can we show cropping image with blur background of image parts? 

### ISSUE THREAD

**Issue by JayMehta711** [ruslanskorb/RSKImageCropper#89]
I want to create cropping image view like whats up ? so can you help me for same.

**Comment by ruslanskorb** [comment]
Hi @JayMehta711,

I think that there is no easy way to do it.

One way is as follows:
1. Add `UIVisualEffectView` with `UIBlurEffect` to the image scroll view.
2. Show it when the user does not drag / scale / rotate the original image, or hide otherwise.
3. Add preview image view that corresponds to your mask above the image scroll view.
4. Crop the original image when the user no longer drag / scale / rotate and place it into the preview image view, or set the image of the preview image view to `nil` otherwise.
5. Use the image from the preview image view as a cropped image.

p.s. If you will implement it I will reopen the issue.
